# Generated by Django 2.2 on 2020-07-20 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiondetails',
            name='fine_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='transactions.Fines'),
        ),
    ]
