# Generated by Django 2.2 on 2020-07-20 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_auto_20200720_1051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactiondetails',
            name='fine_id',
        ),
        migrations.AddField(
            model_name='transactiondetails',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.DeleteModel(
            name='Fines',
        ),
    ]
