# Generated by Django 2.2 on 2020-07-20 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdata',
            options={'verbose_name': 'User Detail Row', 'verbose_name_plural': 'User Data'},
        ),
        migrations.AlterField(
            model_name='userdata',
            name='username',
            field=models.CharField(default='new_user', max_length=10),
        ),
    ]
