# Generated by Django 2.2 on 2020-07-20 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.IntegerField(auto_created=True, unique=True)),
                ('item_name', models.CharField(max_length=50)),
                ('hsn_code', models.CharField(max_length=20)),
                ('publisher', models.CharField(default='NULL', max_length=30)),
                ('shelf', models.CharField(default='NULL', max_length=30)),
                ('item_quantity', models.IntegerField(default=0)),
                ('author', models.CharField(default='Unknown', max_length=30)),
            ],
        ),
    ]
