# Generated by Django 2.2 on 2020-07-21 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemdetails',
            name='id',
        ),
        migrations.AlterField(
            model_name='itemdetails',
            name='item_id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
