# Generated by Django 2.2 on 2020-09-27 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_itemdetails_item_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('category_id', models.IntegerField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=15)),
            ],
        ),
    ]
